-- =============================================================
-- Replace the hardcoded "30 min" slot length and "~€25" price shown
-- in BookingSheet with per-barber defaults stored on the barbers
-- row. Future MISSING #6 (services catalog) will override these
-- per-service, but for now a single default per barber removes the
-- visible inconsistency that every barber looks the same.
--
-- default_slot_minutes: granularity at which availability slots are
--   generated by useAvailability.generateSlots(). Common values: 15,
--   20, 30, 45, 60. Existing barbers keep 30 min.
-- default_price: ballpark price shown in the booking summary.
--   numeric(7,2) supports up to 99999.99 — plenty for haircuts.
-- =============================================================

alter table barbers
  add column if not exists default_slot_minutes int not null default 30
    check (default_slot_minutes > 0 and default_slot_minutes <= 240);

alter table barbers
  add column if not exists default_price numeric(7,2) not null default 25.00
    check (default_price >= 0);
